/* EntityDataEngine1 — browser build.
 *
 * GENERATED by tools/build_browser_engine.py from the live Office Script.
 * Do not hand-edit: regenerate after any engine change, or the HTML clients
 * and the flow will silently disagree.
 *
 * Identical computation to the Office Script; only the data source differs
 * (a JSON dataset instead of Excel tables).
 */
(function (root) {
"use strict";
/**
 * EntityDataEngine - generic entity-profiling Office Script.
 * Evolves the old ReportDataPuller (person + search) into an entity-aware engine.
 *
 * WHY one string parameter:
 *   The Power Automate "Run script" action's parameter list is baked into the
 *   flow. If we added a param every time capability grew, the flow would break.
 *   Instead the parser (Claude call #1) emits ONE JSON DataRequest; this script
 *   takes it single string, JSON.parses it, and returns ONE JSON envelope
 *   string (surfaced to the flow content `result`). New entity types
 *   and filters never change the signature.
 *
 * CONTRACTS: see data-engine-reference.md sec 7 (DataRequest) and sec 8 (envelope).
 *
 * SANDBOX CONSTRAINTS (hard):
 *   - ExcelScript API only. No fetch / TextEncoder / Crypto / Date-parsing libs.
 *   - Params & return are primitives (string in, string out).
 *   - Column access by HEADER NAME, never fixed index.
 *   - Read-only. Deterministic. No workbook mutation.
 *
 * EXTENDING (see reference sec 11):
 *   - New filter  -> add a clause in applyProjectFilters / hoursMatchesFilters /
 *                    costMatchesFilters (one spot each).
 *   - New section -> pushSection(...) inside the relevant build* function; keep
 *                    the title identical to the reference playbook.
 *   - New entity  -> add a build*Profile() and a case in main()'s dispatch.
 */


/* =========================================================================
 * Types
 * ======================================================================= */

const ROW_CAP = 50;
const TREND_MONTH_CAP = 24;

/* =========================================================================
 * Request parsing / defaults
 * ======================================================================= */

function parseRequest(raw) {
    let r;
    try { r = JSON.parse(raw || "{}"); }
    catch (e) { r = { entityType: "unknown", entityValue: null, intent: "profile" }; }
    if (!r.entityType) r.entityType = "unknown";
    if (!r.intent) r.intent = "profile";
    if (r.entityValue === undefined) r.entityValue = null;
    if (!r.filters) r.filters = {};
    return r;
}

/* =========================================================================
 * Workbook access (header-name based, read once)
 * ======================================================================= */



function col(t, header) {
    const i = t.idx[header];
    if (i === undefined) throw new Error("Missing column '" + header + "'");
    return i;
}
function val(t, row, header) { return row[col(t, header)]; }

/* =========================================================================
 * Small helpers
 * ======================================================================= */

function norm(v) { return (v ?? "").toString().trim().toLowerCase(); }
function str(v) { return (v ?? "").toString(); }
function num(v) { const n = Number(v); return isNaN(n) ? 0 : n; }
function money(n) { return Math.round(n * 100) / 100; }
function h1(n) { return Math.round(n * 10) / 10; }
function isTrue(v) { const s = norm(v); return s === "true" || s === "1" || s === "yes"; }
function has(arr) { return !!arr && arr.length > 0; }
function inList(value, list) {
    if (!has(list)) return true;                     // no filter -> pass
    const v = norm(value);
    for (const item of list) if (norm(item) === v) return true;
    return false;
}
/** Parse MM/DD/YYYY -> YYYYMMDD int for comparison; 0 if blank/bad. */
function dnum(v) {
    const s = str(v).trim(); if (!s) return 0;
    const p = s.split("/"); if (p.length !== 3) return 0;
    const m = Number(p[0]), d = Number(p[1]), y = Number(p[2]);
    if (isNaN(m) || isNaN(d) || isNaN(y)) return 0;
    return y * 10000 + m * 100 + d;
}
/** Parse MM/DD/YYYY -> "YYYY-MM" month key; "" if blank/bad. */
function monthKey(v) {
    const s = str(v).trim(); if (!s) return "";
    const p = s.split("/"); if (p.length !== 3) return "";
    const m = Number(p[0]), y = Number(p[2]);
    if (isNaN(m) || isNaN(y) || m < 1 || m > 12 || y < 2000 || y > 2100) return "";
    return y + "-" + (m < 10 ? "0" : "") + m;
}
function addTo(map, key, amt) {
    map[key] = (map[key] || 0) + amt;
}
/** Month->value map to a contiguous zero-filled TrendSeries (null if <2 months of data). */
function trendSeries(key, label, unit, byMonth) {
    const keys = Object.keys(byMonth).filter(k => !!k).sort();
    if (keys.length < 2) return null;                // a single point is not a trend
    const last = keys[keys.length - 1];
    let fy = Number(keys[0].slice(0, 4)), fm = Number(keys[0].slice(5, 7));
    const ly = Number(last.slice(0, 4)), lm = Number(last.slice(5, 7));
    const points = [];
    let guard = 0;
    while ((fy < ly || (fy === ly && fm <= lm)) && guard < 400) {
        const k = fy + "-" + (fm < 10 ? "0" : "") + fm;
        points.push([k, unit === "hours" ? h1(byMonth[k] || 0) : money(byMonth[k] || 0)]);
        fm++; if (fm > 12) { fm = 1; fy++; } guard++;
    }
    const capped = points.slice(-TREND_MONTH_CAP);
    let total = 0; for (const p of capped) total += Number(p[1]);
    return { key, label, unit, points: capped, total: unit === "hours" ? h1(total) : money(total) };
}
function pushTrend(env, s) { if (s) env.trends.push(s); }
function section(title, columns, rows, aggregates) {
    return {
        title, columns, rows: rows.slice(0, ROW_CAP), rowCount: rows.length,
        rowsShown: Math.min(rows.length, ROW_CAP), aggregates
    };
}
function out(env) { return JSON.stringify(env); }

function baseEnvelope(entityType, resolved) {
    return {
        ok: true, entityType, resolvedEntity: resolved, ambiguous: false, candidates: [],
        summary: { headline: "", metrics: {} }, sections: [], rowsSampled: {}, notes: [], error: null,
        trends: []
    };
}
function errEnvelope(entityType, msg) {
    const e = baseEnvelope(entityType, null); e.ok = false; e.error = msg;
    e.summary.headline = msg; return e;
}
function noneEnvelope(entityType, value) {
    const e = baseEnvelope(entityType, null);
    e.summary.headline = "No " + entityType + " matched" + (value ? " '" + value + "'." : ".");
    e.notes.push("Check spelling, or try a fuller name / a ProjectID.");
    return e;
}
function ambiguousEnvelope(entityType, candidates) {
    const e = baseEnvelope(entityType, null);
    e.ambiguous = true; e.candidates = candidates;
    e.summary.headline = "'" + (candidates.length) + "' possible matches - need clarification.";
    return e;
}
function finalize(env) {
    for (const s of env.sections) env.rowsSampled[s.title] = { shown: s.rowsShown, total: s.rowCount };
    if (env.sections.some(s => s.rowCount > s.rowsShown))
        env.notes.push("Row detail capped at " + ROW_CAP + "/section; aggregates cover all rows.");
    return env;
}

/* =========================================================================
 * Filters
 * ======================================================================= */

/** Project-level attribute filters (Status/Type/Priority/City/State/Safety/Value). */
function projectMatches(db, row, f) {
    const P = db.projects;
    if (!inList(val(P, row, "Status"), f.status)) return false;
    if (!inList(val(P, row, "ProjectType"), f.projectType)) return false;
    if (!inList(val(P, row, "PriorityLevel"), f.priority)) return false;
    if (!inList(val(P, row, "City"), f.city)) return false;
    if (!inList(val(P, row, "State"), f.state)) return false;
    if (f.safetyIncident !== undefined && isTrue(val(P, row, "SafetyIncidentFlag")) !== f.safetyIncident) return false;
    const cv = num(val(P, row, "ContractValue"));
    if (f.minContractValue !== undefined && f.minContractValue !== null && cv < f.minContractValue) return false;
    if (f.maxContractValue !== undefined && f.maxContractValue !== null && cv > f.maxContractValue) return false;
    return true;
}
function hoursMatchesFilter(db, row, f) {
    const H = db.hours;
    if (!inList(val(H, row, "Role"), f.role)) return false;
    if (!inList(val(H, row, "TaskCode"), f.taskCode)) return false;
    if (f.overtime !== undefined && isTrue(val(H, row, "OvertimeFlag")) !== f.overtime) return false;
    if (f.dateFrom || f.dateTo) {
        const d = dnum(val(H, row, "Date"));
        if (f.dateFrom && d < dnum(f.dateFrom)) return false;
        if (f.dateTo && d > dnum(f.dateTo)) return false;
    }
    return true;
}
function costMatchesFilter(db, row, f) {
    const C = db.costs;
    if (!inList(val(C, row, "CostCategory"), f.costCategory)) return false;
    if (!inList(val(C, row, "PaymentStatus"), f.paymentStatus)) return false;
    if (f.dateFrom || f.dateTo) {
        const d = dnum(val(C, row, "DateIncurred"));
        if (f.dateFrom && d < dnum(f.dateFrom)) return false;
        if (f.dateTo && d > dnum(f.dateTo)) return false;
    }
    return true;
}

/* =========================================================================
 * PERSON
 * ======================================================================= */

/** Distinct person names (original casing) that partial-match the query across all 5 person columns. */
function resolvePersonNames(db, query) {
    const q = norm(query); const seen = {};
    const add = (v) => { const s = str(v); if (s && (!q || norm(s).indexOf(q) >= 0)) seen[norm(s)] = s; };
    const P = db.projects, H = db.hours, C = db.costs;
    for (const r of P.rows) { add(val(P, r, "ProjectManager")); add(val(P, r, "CrewLead")); }
    for (const r of H.rows) { add(val(H, r, "EmployeeName")); add(val(H, r, "ApprovedBy")); }
    for (const r of C.rows) { add(val(C, r, "ApprovedBy")); }
    return Object.keys(seen).map(k => seen[k]);
}

function personRoleHint(db, name) {
    const n = norm(name); const P = db.projects, H = db.hours, C = db.costs;
    let pm = 0, lead = 0, emp = 0, apprH = 0, apprC = 0;
    for (const r of P.rows) { if (norm(val(P, r, "ProjectManager")) === n) pm++; if (norm(val(P, r, "CrewLead")) === n) lead++; }
    for (const r of H.rows) { if (norm(val(H, r, "EmployeeName")) === n) emp++; if (norm(val(H, r, "ApprovedBy")) === n) apprH++; }
    for (const r of C.rows) { if (norm(val(C, r, "ApprovedBy")) === n) apprC++; }
    const parts = [];
    if (pm) parts.push("PM x" + pm); if (lead) parts.push("Lead x" + lead);
    if (emp) parts.push(emp + " hrs entries"); if (apprH) parts.push("approved " + apprH + " hrs");
    if (apprC) parts.push("approved " + apprC + " costs");
    return parts.length ? parts.join(", ") : "no rows";
}

function buildPerson(db, req) {
    const names = resolvePersonNames(db, req.entityValue || "");
    if (names.length === 0) return noneEnvelope("person", req.entityValue);
    if (names.length > 1) {
        return ambiguousEnvelope("person", names.map(nm =>
            ({ label: nm, hint: personRoleHint(db, nm), entityType: "person", entityValue: nm })));
    }
    const name = names[0]; const n = norm(name); const f = req.filters;
    const P = db.projects, H = db.hours, C = db.costs;
    const env = baseEnvelope("person", name);

    // ---- managed / led projects (apply project attribute filters to the lists) ----
    const managedAll = [], ledAll = [];
    for (const r of P.rows) {
        if (norm(val(P, r, "ProjectManager")) === n) managedAll.push(r);
        if (norm(val(P, r, "CrewLead")) === n) ledAll.push(r);
    }
    const managed = managedAll.filter(r => projectMatches(db, r, f));
    const led = ledAll.filter(r => projectMatches(db, r, f));

    const projRow = (r) => [num(val(P, r, "ProjectID")), str(val(P, r, "ProjectName")),
    str(val(P, r, "ClientName")), str(val(P, r, "Status")), money(num(val(P, r, "ContractValue")))];
    const statusBreak = (rows) => {
        const m = {}; for (const r of rows) addTo(m, str(val(P, r, "Status")), 1); return m;
    };
    const cvSum = (rows) => { let s = 0; for (const r of rows) s += num(val(P, r, "ContractValue")); return money(s); };

    // ---- labor employee ----
    let hoursWorked = 0, otHours = 0, hourEntries = 0;
    const byRole = {}, byTask = {}, projSet = {};
    const hrsByMonth = {};
    const laborRows = [];
    for (const r of H.rows) {
        if (norm(val(H, r, "EmployeeName")) !== n) continue;
        if (!hoursMatchesFilter(db, r, f)) continue;
        const hw = num(val(H, r, "HoursWorked"));
        hoursWorked += hw; hourEntries++;
        if (isTrue(val(H, r, "OvertimeFlag"))) otHours += hw;
        addTo(byRole, str(val(H, r, "Role")), hw); addTo(byTask, str(val(H, r, "TaskCode")), hw);
        addTo(hrsByMonth, monthKey(val(H, r, "Date")), hw);
        projSet[str(val(H, r, "ProjectID"))] = true;
        laborRows.push([num(val(H, r, "ProjectID")), str(val(H, r, "Date")), str(val(H, r, "Role")),
        str(val(H, r, "TaskCode")), h1(hw)]);
    }

    // ---- approvals ----
    let apprHrsCount = 0, apprHrsTotal = 0, apprCostCount = 0, apprCostTotal = 0;
    for (const r of H.rows) if (norm(val(H, r, "ApprovedBy")) === n) { apprHrsCount++; apprHrsTotal += num(val(H, r, "HoursWorked")); }
    for (const r of C.rows) if (norm(val(C, r, "ApprovedBy")) === n) { apprCostCount++; apprCostTotal += num(val(C, r, "Amount")); }

    // ---- metrics (totals always over the unfiltered role sets for context) ----
    const activeManaged = managedAll.filter(r => norm(val(P, r, "Status")) === "active").length;
    env.summary.metrics = {
        projectsManaged: managedAll.length, activeProjectsManaged: activeManaged,
        contractValueManaged: cvSum(managedAll), projectsLed: ledAll.length,
        hoursWorked: h1(hoursWorked), hourEntries, overtimeHours: h1(otHours),
        hoursApprovedCount: apprHrsCount, costsApprovedCount: apprCostCount, costsApprovedAmount: money(apprCostTotal)
    };
    env.summary.headline = name + " - " +
        (managedAll.length ? "PM on " + managedAll.length + " projects (" + activeManaged + " active), $" + cvSum(managedAll).toFixed(0) + " contract value" : "not a project manager") +
        (ledAll.length ? "; crew lead on " + ledAll.length : "") +
        (hourEntries ? "; " + h1(hoursWorked) + " hrs logged" : "") + ".";

    // ---- sections ----
    env.sections.push(section("Roles Held", ["Role", "Count"], [
        ["Project Manager", managedAll.length], ["Crew Lead", ledAll.length],
        ["Field Employee (entries)", hourEntries], ["Approver - Hours", apprHrsCount], ["Approver - Costs", apprCostCount]
    ], { roleHint: personRoleHint(db, name) }));

    env.sections.push(section("Projects Managed", ["ProjectID", "ProjectName", "Client", "Status", "ContractValue"],
        managed.map(r => projRow(r)), { count: managed.length, totalContractValue: cvSum(managed), statusBreakdown: statusBreak(managed) }));

    if (ledAll.length) env.sections.push(section("Projects Led (Crew Lead)",
        ["ProjectID", "ProjectName", "Client", "Status", "ContractValue"],
        led.map(r => projRow(r)), { count: led.length, totalContractValue: cvSum(led), statusBreakdown: statusBreak(led) }));

    if (hourEntries) env.sections.push(section("Labor (as field employee)",
        ["ProjectID", "Date", "Role", "TaskCode", "HoursWorked"], laborRows,
        {
            totalHours: h1(hoursWorked), entries: hourEntries, overtimeHours: h1(otHours),
            distinctProjects: Object.keys(projSet).length, hoursByRole: byRole, hoursByTask: byTask
        }));

    if (apprHrsCount || apprCostCount) env.sections.push(section("Approvals",
        ["Type", "Count", "Total"], [
        ["Hours approved", apprHrsCount, h1(apprHrsTotal)],
        ["Costs approved", apprCostCount, money(apprCostTotal)]
    ], { hoursApprovedTotal: h1(apprHrsTotal), costsApprovedTotal: money(apprCostTotal) }));

    pushTrend(env, trendSeries("hours", "Hours worked by month", "hours", hrsByMonth));
    return finalize(env);
}

/* =========================================================================
 * VENDOR
 * ======================================================================= */

function resolveDistinct(db, table, header, query) {
    const q = norm(query); const seen = {};
    for (const r of table.rows) { const s = str(val(table, r, header)); if (s && (!q || norm(s).indexOf(q) >= 0)) seen[norm(s)] = s; }
    return Object.keys(seen).map(k => seen[k]);
}

function buildVendor(db, req) {
    const C = db.costs, P = db.projects;
    const vendors = resolveDistinct(db, C, "VendorName", req.entityValue || "");
    if (vendors.length === 0) return noneEnvelope("vendor", req.entityValue);
    if (vendors.length > 1) {
        return ambiguousEnvelope("vendor", vendors.map(v => {
            let tot = 0; for (const r of C.rows) if (norm(val(C, r, "VendorName")) === norm(v)) tot += num(val(C, r, "Amount"));
            return { label: v, hint: "$" + money(tot).toFixed(0) + " total spend", entityType: "vendor", entityValue: v };
        }));
    }
    const vendor = vendors[0]; const vn = norm(vendor); const f = req.filters;
    const env = baseEnvelope("vendor", vendor);

    const byCat = {}, catCount = {};
    const byPay = {}, payCount = {};
    const byProj = {};
    const spendByMonth = {};
    const lines = [];
    let total = 0, lineCount = 0;
    for (const r of C.rows) {
        if (norm(val(C, r, "VendorName")) !== vn) continue;
        if (!costMatchesFilter(db, r, f)) continue;
        const amt = num(val(C, r, "Amount")); total += amt; lineCount++;
        addTo(byCat, str(val(C, r, "CostCategory")), amt); addTo(catCount, str(val(C, r, "CostCategory")), 1);
        addTo(byPay, str(val(C, r, "PaymentStatus")), amt); addTo(payCount, str(val(C, r, "PaymentStatus")), 1);
        addTo(byProj, str(val(C, r, "ProjectID")), amt);
        addTo(spendByMonth, monthKey(val(C, r, "DateIncurred")), amt);
        lines.push([num(val(C, r, "CostID")), num(val(C, r, "ProjectID")), str(val(C, r, "CostCategory")),
        str(val(C, r, "Description")), money(amt), str(val(C, r, "DateIncurred")), str(val(C, r, "PaymentStatus")),
        str(val(C, r, "InvoiceNumber"))]);
    }
    env.summary.metrics = {
        totalSpend: money(total), lineCount, projectsServed: Object.keys(byProj).length,
        overdueAmount: money(byPay["Overdue"] || 0), pendingAmount: money(byPay["Pending"] || 0), paidAmount: money(byPay["Paid"] || 0)
    };
    env.summary.headline = vendor + " - $" + money(total).toFixed(0) + " across " + lineCount + " line(s), " +
        Object.keys(byProj).length + " project(s)" + ((byPay["Overdue"] || 0) > 0 ? "; $" + money(byPay["Overdue"]).toFixed(0) + " overdue" : "") + ".";

    const catRows = Object.keys(byCat).map(k => [k, money(byCat[k]), catCount[k]]);
    env.sections.push(section("Spend by Category", ["CostCategory", "Amount", "Lines"], catRows, { total: money(total) }));
    const payRows = Object.keys(byPay).map(k => [k, money(byPay[k]), payCount[k]]);
    env.sections.push(section("Payment Status", ["PaymentStatus", "Amount", "Lines"], payRows, {
        overdue: money(byPay["Overdue"] || 0), pending: money(byPay["Pending"] || 0), paid: money(byPay["Paid"] || 0)
    }));
    // projects served (with project names)
    const projRows = Object.keys(byProj).map(pid => {
        const pr = findProjectById(db, Number(pid));
        return [Number(pid), pr ? str(val(P, pr, "ProjectName")) : "(unknown)", money(byProj[pid])];
    });
    env.sections.push(section("Projects Served", ["ProjectID", "ProjectName", "AmountToProject"], projRows, { count: projRows.length }));
    env.sections.push(section("Cost Lines (sample)",
        ["CostID", "ProjectID", "Category", "Description", "Amount", "DateIncurred", "PaymentStatus", "InvoiceNumber"],
        lines, { total: money(total) }));
    pushTrend(env, trendSeries("spend", "Spend by month", "money", spendByMonth));
    return finalize(env);
}

/* =========================================================================
 * CLIENT
 * ======================================================================= */

function buildClient(db, req) {
    const P = db.projects, H = db.hours, C = db.costs;
    const clients = resolveDistinct(db, P, "ClientName", req.entityValue || "");
    if (clients.length === 0) return noneEnvelope("client", req.entityValue);
    if (clients.length > 1) {
        return ambiguousEnvelope("client", clients.map(cl => {
            let cnt = 0; for (const r of P.rows) if (norm(val(P, r, "ClientName")) === norm(cl)) cnt++;
            return { label: cl, hint: cnt + " project(s)", entityType: "client", entityValue: cl };
        }));
    }
    const client = clients[0]; const cn = norm(client); const f = req.filters;
    const env = baseEnvelope("client", client);

    const projRows = []; const pids = {};
    let cvTotal = 0, activeCount = 0;
    const statusBreak = {}, typeBreak = {};
    for (const r of P.rows) {
        if (norm(val(P, r, "ClientName")) !== cn) continue;
        if (!projectMatches(db, r, f)) continue;
        pids[str(val(P, r, "ProjectID"))] = true;
        cvTotal += num(val(P, r, "ContractValue"));
        if (norm(val(P, r, "Status")) === "active") activeCount++;
        addTo(statusBreak, str(val(P, r, "Status")), 1); addTo(typeBreak, str(val(P, r, "ProjectType")), 1);
        projRows.push([num(val(P, r, "ProjectID")), str(val(P, r, "ProjectName")), str(val(P, r, "Status")),
        str(val(P, r, "ProjectType")), money(num(val(P, r, "ContractValue")))]);
    }
    // actual cost-to-date across their projects
    let laborCost = 0, otherCosts = 0; const costByCat = {};
    const laborByMonth = {}, costsByMonth = {};
    for (const r of H.rows) if (pids[str(val(H, r, "ProjectID"))]) {
        const lc = num(val(H, r, "HoursWorked")) * num(val(H, r, "HourlyRate"));
        laborCost += lc; addTo(laborByMonth, monthKey(val(H, r, "Date")), lc);
    }
    for (const r of C.rows) if (pids[str(val(C, r, "ProjectID"))]) { const a = num(val(C, r, "Amount")); otherCosts += a; addTo(costByCat, str(val(C, r, "CostCategory")), a); addTo(costsByMonth, monthKey(val(C, r, "DateIncurred")), a); }
    const actual = laborCost + otherCosts;

    env.summary.metrics = {
        projectCount: projRows.length, totalContractValue: money(cvTotal), activeCount,
        actualCostToDate: money(actual), laborCost: money(laborCost), otherCosts: money(otherCosts)
    };
    env.summary.headline = client + " - " + projRows.length + " project(s), $" + money(cvTotal).toFixed(0) +
        " contract value, ~$" + money(actual).toFixed(0) + " actual cost to date.";
    env.sections.push(section("Projects", ["ProjectID", "ProjectName", "Status", "ProjectType", "ContractValue"],
        projRows, { count: projRows.length, totalContractValue: money(cvTotal), statusBreakdown: statusBreak, typeBreakdown: typeBreak }));
    env.sections.push(section("Financial Roll-up", ["Measure", "Value"], [
        ["Total ContractValue", money(cvTotal)], ["Labor cost", money(laborCost)],
        ["Other costs", money(otherCosts)], ["Actual cost to date", money(actual)],
        ["Contract minus actual", money(cvTotal - actual)]
    ], { contractValue: money(cvTotal), actual: money(actual), margin: money(cvTotal - actual) }));
    env.sections.push(section("Cost by Category", ["CostCategory", "Amount"],
        Object.keys(costByCat).map(k => [k, money(costByCat[k])]), { total: money(otherCosts) }));
    pushTrend(env, trendSeries("costs", "Project costs by month", "money", costsByMonth));
    pushTrend(env, trendSeries("laborCost", "Labor cost by month", "money", laborByMonth));
    return finalize(env);
}

/* =========================================================================
 * PROJECT
 * ======================================================================= */

function findProjectById(db, id) {
    const P = db.projects;
    for (const r of P.rows) if (num(val(P, r, "ProjectID")) === id) return r;
    return null;
}

function buildProject(db, req) {
    const P = db.projects, H = db.hours, C = db.costs;
    const raw = str(req.entityValue).trim();
    let candidates = [];
    if (raw && /^\d+$/.test(raw)) {
        const r = findProjectById(db, Number(raw)); if (r) candidates = [r];
    } else {
        const q = norm(raw);
        for (const r of P.rows) if (!q || norm(val(P, r, "ProjectName")).indexOf(q) >= 0) candidates.push(r);
    }
    if (candidates.length === 0) return noneEnvelope("project", req.entityValue);
    if (candidates.length > 1) {
        return ambiguousEnvelope("project", candidates.slice(0, 25).map(r => ({
            label: str(val(P, r, "ProjectName")) + " (#" + num(val(P, r, "ProjectID")) + ")",
            hint: str(val(P, r, "ClientName")) + " - " + str(val(P, r, "City")) + ", " + str(val(P, r, "State")) + " - " + str(val(P, r, "Status")),
            entityType: "project", entityValue: str(num(val(P, r, "ProjectID")))
        })));
    }
    const r = candidates[0]; const pid = num(val(P, r, "ProjectID"));
    const env = baseEnvelope("project", str(val(P, r, "ProjectName")) + " (#" + pid + ")");

    let actualHours = 0, laborCost = 0; const byRole = {}, byTask = {}, workers = {};
    const hrsByMonth = {};
    const hourRows = [];
    for (const hr of H.rows) {
        if (num(val(H, hr, "ProjectID")) !== pid) continue;
        const hw = num(val(H, hr, "HoursWorked")), rate = num(val(H, hr, "HourlyRate"));
        actualHours += hw; laborCost += hw * rate;
        addTo(byRole, str(val(H, hr, "Role")), hw); addTo(byTask, str(val(H, hr, "TaskCode")), hw);
        addTo(hrsByMonth, monthKey(val(H, hr, "Date")), hw);
        workers[norm(val(H, hr, "EmployeeName"))] = true;
        hourRows.push([str(val(H, hr, "EmployeeName")), str(val(H, hr, "Date")), str(val(H, hr, "Role")), str(val(H, hr, "TaskCode")), h1(hw)]);
    }
    let costsTotal = 0; const costByCat = {}, costCatCount = {};
    const costsByMonth = {};
    const costRows = [];
    for (const cr of C.rows) {
        if (num(val(C, cr, "ProjectID")) !== pid) continue;
        const a = num(val(C, cr, "Amount")); costsTotal += a;
        addTo(costByCat, str(val(C, cr, "CostCategory")), a); addTo(costCatCount, str(val(C, cr, "CostCategory")), 1);
        addTo(costsByMonth, monthKey(val(C, cr, "DateIncurred")), a);
        costRows.push([num(val(C, cr, "CostID")), str(val(C, cr, "CostCategory")), str(val(C, cr, "VendorName")),
        money(a), str(val(C, cr, "PaymentStatus")), str(val(C, cr, "DateIncurred"))]);
    }
    const cv = num(val(P, r, "ContractValue")), budgetedHours = num(val(P, r, "BudgetedHours"));
    const budgetedMat = num(val(P, r, "BudgetedMaterialCost"));
    const totalActual = laborCost + costsTotal, variance = cv - totalActual;

    env.summary.metrics = {
        contractValue: money(cv), actualHours: h1(actualHours), budgetedHours,
        laborCost: money(laborCost), costsTotal: money(costsTotal), totalActualCost: money(totalActual),
        budgetVariance: money(variance), budgetedMaterialCost: money(budgetedMat)
    };
    env.summary.headline = str(val(P, r, "ProjectName")) + " (#" + pid + ") - " + str(val(P, r, "Status")) +
        ", $" + money(cv).toFixed(0) + " contract; actual ~$" + money(totalActual).toFixed(0) +
        " (" + (variance >= 0 ? "$" + money(variance).toFixed(0) + " under" : "$" + money(-variance).toFixed(0) + " over") + ").";

    env.sections.push(section("Overview", ["Field", "Value"], [
        ["ProjectName", str(val(P, r, "ProjectName"))], ["Client", str(val(P, r, "ClientName"))],
        ["Status", str(val(P, r, "Status"))], ["ProjectType", str(val(P, r, "ProjectType"))],
        ["ProjectManager", str(val(P, r, "ProjectManager"))], ["CrewLead", str(val(P, r, "CrewLead"))],
        ["City/State", str(val(P, r, "City")) + ", " + str(val(P, r, "State"))], ["Priority", str(val(P, r, "PriorityLevel"))],
        ["StartDate", str(val(P, r, "StartDate"))], ["EndDate", str(val(P, r, "EndDate"))],
        ["ContractValue", money(cv)], ["PermitNumber", str(val(P, r, "PermitNumber"))],
        ["SafetyIncidentFlag", str(val(P, r, "SafetyIncidentFlag"))]
    ], {}));
    env.sections.push(section("Budget vs Actual", ["Measure", "Budget/Contract", "Actual", "Variance"], [
        ["Hours", budgetedHours, h1(actualHours), h1(budgetedHours - actualHours)],
        ["Dollars", money(cv), money(totalActual), money(variance)]
    ], { variancePct: cv ? Math.round((variance / cv) * 1000) / 10 : "" }));
    env.sections.push(section("Costs by Category", ["CostCategory", "Amount", "Lines"],
        Object.keys(costByCat).map(k => [k, money(costByCat[k]), costCatCount[k]]), { total: money(costsTotal) }));
    env.sections.push(section("Labor Summary", ["Metric", "Value"], [
        ["Total hours", h1(actualHours)], ["Distinct workers", Object.keys(workers).length]
    ], { hoursByRole: byRole, hoursByTask: byTask }));
    env.sections.push(section("Cost Lines (sample)", ["CostID", "Category", "Vendor", "Amount", "PaymentStatus", "DateIncurred"], costRows, {}));
    env.sections.push(section("Hours (sample)", ["Employee", "Date", "Role", "TaskCode", "HoursWorked"], hourRows, {}));
    pushTrend(env, trendSeries("costs", "Costs by month", "money", costsByMonth));
    pushTrend(env, trendSeries("hours", "Hours by month", "hours", hrsByMonth));
    return finalize(env);
}

/* =========================================================================
 * SEGMENT (filtered project set)
 * ======================================================================= */

/** ProjectIDs having >=1 child cost/hours row matching the child filters (and the summed matching amount for costs). */
function projectsWithMatchingCosts(db, f) {
    const C = db.costs; const ids = {}, amt = {};
    for (const r of C.rows) if (costMatchesFilter(db, r, f)) { const pid = str(val(C, r, "ProjectID")); ids[pid] = true; addTo(amt, pid, num(val(C, r, "Amount"))); }
    return { ids, amt };
}
function projectsWithMatchingHours(db, f) {
    const H = db.hours; const ids = {};
    for (const r of H.rows) if (hoursMatchesFilter(db, r, f)) ids[str(val(H, r, "ProjectID"))] = true;
    return ids;
}

function buildSegment(db, req) {
    const P = db.projects; const f = req.filters;
    const env = baseEnvelope("segment", null);
    const costFiltersActive = has(f.costCategory) || has(f.paymentStatus);
    const hoursFiltersActive = has(f.role) || has(f.taskCode) || f.overtime !== undefined;
    const dateActive = !!(f.dateFrom || f.dateTo);
    const costMatch = (costFiltersActive || dateActive) ? projectsWithMatchingCosts(db, f) : null;
    const hoursIds = (hoursFiltersActive || dateActive) ? projectsWithMatchingHours(db, f) : null;

    const rows = []; let cvTotal = 0, matchAmt = 0;
    const statusBreak = {}, typeBreak = {}, cityBreak = {};
    for (const r of P.rows) {
        if (!projectMatches(db, r, f)) continue;
        const pid = str(val(P, r, "ProjectID"));
        if (costMatch && !costMatch.ids[pid]) continue;
        if (hoursIds && !hoursIds[pid]) continue;
        cvTotal += num(val(P, r, "ContractValue"));
        addTo(statusBreak, str(val(P, r, "Status")), 1); addTo(typeBreak, str(val(P, r, "ProjectType")), 1); addTo(cityBreak, str(val(P, r, "City")), 1);
        const base = [num(val(P, r, "ProjectID")), str(val(P, r, "ProjectName")), str(val(P, r, "ClientName")),
        str(val(P, r, "Status")), str(val(P, r, "City")), str(val(P, r, "PriorityLevel")), money(num(val(P, r, "ContractValue")))];
        if (costMatch) { const a = costMatch.amt[pid] || 0; matchAmt += a; base.push(money(a)); }
        rows.push(base);
    }
    const cols = ["ProjectID", "ProjectName", "Client", "Status", "City", "Priority", "ContractValue"];
    if (costMatch) cols.push("MatchingCostAmount");

    env.summary.metrics = { matchCount: rows.length, totalContractValue: money(cvTotal) };
    if (costMatch) env.summary.metrics["matchingCostTotal"] = money(matchAmt);
    env.summary.headline = rows.length + " project(s) match" + (costMatch ? " - $" + money(matchAmt).toFixed(0) + " in matching costs" : "") +
        "; $" + money(cvTotal).toFixed(0) + " total contract value.";
    env.sections.push(section("Matching Projects", cols, rows,
        { count: rows.length, totalContractValue: money(cvTotal), statusBreakdown: statusBreak }));
    env.sections.push(section("Breakdowns", ["Dimension", "Value", "Count"],
        breakdownRows("Status", statusBreak).concat(breakdownRows("ProjectType", typeBreak)).concat(breakdownRows("City", cityBreak)),
        { byStatus: statusBreak, byType: typeBreak, byCity: cityBreak }));
    return finalize(env);
}
function breakdownRows(dim, m) {
    return Object.keys(m).map(k => [dim, k, m[k]]);
}

/* =========================================================================
 * OVERVIEW / RANKING
 * ======================================================================= */

function buildOverview(db, req) {
    const P = db.projects, H = db.hours, C = db.costs; const f = req.filters;
    const rk = req.ranking || { dimension: "contractValue", groupBy: "projectManager", order: "desc", top: 5 };
    const groupBy = rk.groupBy || "projectManager";
    const dim = rk.dimension || "contractValue";
    const top = rk.top && rk.top > 0 ? rk.top : 5;
    const env = baseEnvelope("overview", null);
    const KNOWN_GROUPS = ["projectManager", "crewLead", "client", "vendor", "city", "state", "status", "projectType", "project", "projectName", "projectID"];
    if (KNOWN_GROUPS.indexOf(groupBy) < 0) env.notes.push("Unrecognized groupBy '" + groupBy + "' - grouped by projectManager instead.");

    // Aggregate a value per group key.
    const value = {}, count = {};
    const groupKeyForProject = (r) => {
        switch (groupBy) {
            case "projectManager": return str(val(P, r, "ProjectManager"));
            case "crewLead": return str(val(P, r, "CrewLead"));
            case "client": return str(val(P, r, "ClientName"));
            case "city": return str(val(P, r, "City"));
            case "state": return str(val(P, r, "State"));
            case "status": return str(val(P, r, "Status"));
            case "projectType": return str(val(P, r, "ProjectType"));
            case "project": case "projectName": case "projectID":
                return str(val(P, r, "ProjectName")) + " (#" + num(val(P, r, "ProjectID")) + ")";
            default: return str(val(P, r, "ProjectManager"));
        }
    };

    if (groupBy === "vendor") {
        // spend by vendor
        for (const r of C.rows) { if (!costMatchesFilter(db, r, f)) continue; const k = str(val(C, r, "VendorName")); addTo(value, k, num(val(C, r, "Amount"))); addTo(count, k, 1); }
    } else if (dim === "spend" || dim === "hours" || dim === "laborCost" || dim === "variance") {
        // need per-project child roll-ups grouped by project's group key
        // (child rows respect the request's cost/hour filters, like the vendor branch)
        const projGroup = {}; const cvByGroup = {};
        for (const r of P.rows) {
            if (!projectMatches(db, r, f)) continue;
            const k = groupKeyForProject(r); projGroup[str(val(P, r, "ProjectID"))] = k;
            addTo(cvByGroup, k, num(val(P, r, "ContractValue"))); addTo(count, k, 1);
        }
        if (dim === "spend") for (const r of C.rows) { const g = projGroup[str(val(C, r, "ProjectID"))]; if (g && costMatchesFilter(db, r, f)) addTo(value, g, num(val(C, r, "Amount"))); }
        if (dim === "hours") for (const r of H.rows) { const g = projGroup[str(val(H, r, "ProjectID"))]; if (g && hoursMatchesFilter(db, r, f)) addTo(value, g, num(val(H, r, "HoursWorked"))); }
        if (dim === "laborCost") for (const r of H.rows) { const g = projGroup[str(val(H, r, "ProjectID"))]; if (g && hoursMatchesFilter(db, r, f)) addTo(value, g, num(val(H, r, "HoursWorked")) * num(val(H, r, "HourlyRate"))); }
        if (dim === "variance") {
            const actual = {};
            for (const r of H.rows) { const g = projGroup[str(val(H, r, "ProjectID"))]; if (g && hoursMatchesFilter(db, r, f)) addTo(actual, g, num(val(H, r, "HoursWorked")) * num(val(H, r, "HourlyRate"))); }
            for (const r of C.rows) { const g = projGroup[str(val(C, r, "ProjectID"))]; if (g && costMatchesFilter(db, r, f)) addTo(actual, g, num(val(C, r, "Amount"))); }
            for (const k of Object.keys(cvByGroup)) value[k] = cvByGroup[k] - (actual[k] || 0);
        }
        const childFiltersActive = has(f.costCategory) || has(f.paymentStatus) || has(f.role) || has(f.taskCode) || f.overtime !== undefined || !!(f.dateFrom || f.dateTo);
        if (childFiltersActive) env.notes.push("Cost/hour row filters applied to the " + dim + " roll-up" + (dim === "variance" ? " (actual-cost side)" : "") + ".");
    } else {
        // contractValue or jobCount, grouped by a project attribute.
        // Child cost/hour filters can't scope these project-level values, so they
        // restrict WHICH projects count instead - segment-style membership, same
        // activity rules (reference sec 7: filters combine freely).
        const cFA = has(f.costCategory) || has(f.paymentStatus);
        const hFA = has(f.role) || has(f.taskCode) || f.overtime !== undefined;
        const dA = !!(f.dateFrom || f.dateTo);
        const costIds = (cFA || dA) ? projectsWithMatchingCosts(db, f).ids : null;
        const hourIds = (hFA || dA) ? projectsWithMatchingHours(db, f) : null;
        for (const r of P.rows) {
            if (!projectMatches(db, r, f)) continue;
            const pid = str(val(P, r, "ProjectID"));
            if (costIds && !costIds[pid]) continue;
            if (hourIds && !hourIds[pid]) continue;
            const k = groupKeyForProject(r);
            addTo(value, k, dim === "jobCount" ? 1 : num(val(P, r, "ContractValue")));
            addTo(count, k, 1);
        }
        if (costIds || hourIds) env.notes.push("Cost/hour row filters restricted the project set for the " + dim + " ranking (only projects with matching activity count).");
    }

    let keys = Object.keys(value).filter(k => k !== "");
    keys.sort((a, b) => (rk.order === "asc" ? value[a] - value[b] : value[b] - value[a]));
    const leader = keys.slice(0, top).map(k => [k, money(value[k]), count[k] || 0]);
    let grand = 0; for (const k of keys) grand += value[k];
    let grandCount = 0; for (const k of keys) grandCount += (count[k] || 0);

    const fmtDim = (v) => dim === "hours" ? h1(v) + " hrs"
        : dim === "jobCount" ? Math.round(v) + " job(s)"
            : (v < 0 ? "-$" + money(-v).toFixed(0) : "$" + money(v).toFixed(0));
    env.summary.metrics = { groups: keys.length, grandTotal: money(grand), grandCount: grandCount, dimension: dim, groupBy };
    // A "metric" intent with no explicit ranking is a total/count question, not a
    // leaderboard question. The numbers were always computed; only the headline and
    // a Totals section were missing, so the answerer could not see them.
    const metricIntent = req.intent === "metric" && !req.ranking;
    env.summary.headline = metricIntent
        ? (grandCount + " project(s) match; " + fmtDim(grand) + " total " + dim + ".")
        : ("Top " + Math.min(top, keys.length) + " by " + dim + " (" + groupBy + "): " +
            (leader.length ? leader[0][0] + " = " + fmtDim(Number(leader[0][1])) : "no data") + ".");
    if (metricIntent) env.sections.push(section("Totals", ["Metric", "Value"],
        [["Projects", grandCount], ["Total " + dim, money(grand)]],
        { grandTotal: money(grand), projects: grandCount }));
    env.sections.push(section("Leaderboard", [groupBy, dim, "Count"], leader, { grandTotal: money(grand), groups: keys.length }));
    return finalize(env);
}

/* =========================================================================
 * COMPARISON (persons)
 * ======================================================================= */

function comparePersons(db, req) {
    const names = (req.compare && req.compare.length ? req.compare : [req.entityValue || ""]).filter(x => !!x);
    const env = baseEnvelope("person", null);
    const rows = []; const resolvedLabels = [];
    for (const nm of names) {
        const matched = resolvePersonNames(db, nm);
        if (matched.length !== 1) {
            // If any side is ambiguous/none, surface that rather than compare wrongly.
            if (matched.length === 0) { env.notes.push("No match for '" + nm + "'."); continue; }
            return ambiguousEnvelope("person", matched.map(m =>
                ({ label: m, hint: personRoleHint(db, m), entityType: "person", entityValue: m })));
        }
        const one = buildPerson(db, { entityType: "person", entityValue: matched[0], intent: "profile", filters: {} });
        const m = one.summary.metrics;
        resolvedLabels.push(matched[0]);
        rows.push([matched[0], Number(m["projectsManaged"]), Number(m["activeProjectsManaged"]),
        Number(m["contractValueManaged"]), Number(m["projectsLed"]), Number(m["hoursWorked"]),
        Number(m["costsApprovedCount"])]);
    }
    env.resolvedEntity = resolvedLabels.join(" vs ");
    env.summary.headline = "Comparison: " + resolvedLabels.join(" vs ") + ".";
    env.sections.push(section("Comparison",
        ["Person", "ProjectsManaged", "ActiveManaged", "ContractValueManaged", "ProjectsLed", "HoursWorked", "CostsApproved"],
        rows, { people: resolvedLabels.length }));
    return finalize(env);
}

/* ---- data source: JSON dataset instead of Excel tables ---- */
function tableFrom(t) {
    const headers = (t.headers || []).map(h => (h == null ? "" : String(h)));
    const idx = {};
    for (let i = 0; i < headers.length; i++) idx[headers[i]] = i;
    return { headers: headers, rows: t.rows || [], idx: idx };
}
function dbFrom(dataset) {
    return {
        projects: tableFrom(dataset.ProjectsTable),
        hours: tableFrom(dataset.HoursTable),
        costs: tableFrom(dataset.CostsTable)
    };
}
/* Same dispatch as the Office Script's main(), same error envelope contract. */
function runRequest(dataset, requestJson) {
    try {
        const req = parseRequest(typeof requestJson === "string"
            ? requestJson : JSON.stringify(requestJson));
        const db = dbFrom(dataset);
        switch (req.entityType) {
            case "person": return req.intent === "comparison"
                ? comparePersons(db, req) : buildPerson(db, req);
            case "vendor": return buildVendor(db, req);
            case "client": return buildClient(db, req);
            case "project": return buildProject(db, req);
            case "segment": return buildSegment(db, req);
            case "overview": return buildOverview(db, req);
            default: return errEnvelope(req.entityType,
                "Unknown entityType '" + req.entityType + "'.");
        }
    } catch (e) {
        return errEnvelope("unknown", "Engine error: " + (e && e.message ? e.message : e));
    }
}
root.ReportEngine = { run: runRequest, version: "browser-1" };
})(typeof window !== "undefined" ? window : globalThis);
